import {
  sql,
} from 'drizzle-orm';
import {
  bigint,
  boolean,
  date,
  integer,
  index,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

const createdAt = timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updatedAt = timestamp('updated_at', { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date());

export const organizations = pgTable('organizations', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  createdAt,
  updatedAt,
});

export const businessUnits = pgTable('business_units', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  label: text('label').notNull().default('Divisions'),
  color: text('color'),
  isActive: boolean('is_active').notNull().default(true),
  createdAt,
  updatedAt,
});

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  email: text('email').unique(),
  phone: text('phone'),
  isActive: boolean('is_active').notNull().default(true),
  createdAt,
  updatedAt,
});

export const userPasswordCredentials = pgTable('user_password_credentials', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  passwordSalt: text('password_salt').notNull(),
  passwordIterations: integer('password_iterations').notNull().default(310000),
  lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
  createdAt,
  updatedAt,
}, (table) => ({
  userIdx: uniqueIndex('user_password_credentials_user_idx').on(table.userId),
}));

export const userSessions = pgTable('user_sessions', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  tokenHash: text('token_hash').notNull().unique(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
  createdAt,
  updatedAt,
});

export const roles = pgTable('roles', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  key: text('key').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  createdAt,
  updatedAt,
}, (table) => ({
  orgKeyIdx: uniqueIndex('roles_org_key_idx').on(table.organizationId, table.key),
}));

export const permissions = pgTable('permissions', {
  id: uuid('id').primaryKey().defaultRandom(),
  key: text('key').notNull().unique(),
  description: text('description'),
  createdAt,
  updatedAt,
});

export const rolePermissions = pgTable('role_permissions', {
  id: uuid('id').primaryKey().defaultRandom(),
  roleId: uuid('role_id').notNull().references(() => roles.id, { onDelete: 'cascade' }),
  permissionId: uuid('permission_id').notNull().references(() => permissions.id, { onDelete: 'cascade' }),
  createdAt,
  updatedAt,
}, (table) => ({
  rolePermissionIdx: uniqueIndex('role_permissions_role_permission_idx').on(table.roleId, table.permissionId),
}));

export const userRoles = pgTable('user_roles', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  roleId: uuid('role_id').notNull().references(() => roles.id, { onDelete: 'cascade' }),
  createdAt,
  updatedAt,
}, (table) => ({
  userRoleIdx: uniqueIndex('user_roles_user_role_idx').on(table.userId, table.roleId),
}));

export const businessUnitMemberships = pgTable('business_unit_memberships', {
  id: uuid('id').primaryKey().defaultRandom(),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  userId: uuid('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  roleId: uuid('role_id').references(() => roles.id, { onDelete: 'set null' }),
  isPrimary: boolean('is_primary').notNull().default(false),
  createdAt,
  updatedAt,
}, (table) => ({
  membershipIdx: uniqueIndex('business_unit_memberships_unique_idx').on(table.businessUnitId, table.userId),
}));

export const contacts = pgTable('contacts', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  primaryBusinessUnitId: uuid('primary_business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  name: text('name').notNull(),
  companyName: text('company_name'),
  phone: text('phone'),
  email: text('email'),
  address: text('address'),
  sourceLabel: text('source_label'),
  isDoNotCall: boolean('is_do_not_call').notNull().default(false),
  isWrongNumber: boolean('is_wrong_number').notNull().default(false),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  archivedByUserId: uuid('archived_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  archiveReason: text('archive_reason'),
  createdAt,
  updatedAt,
});

export const contactPhoneNumbers = pgTable('contact_phone_numbers', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  contactId: uuid('contact_id').notNull().references(() => contacts.id, { onDelete: 'cascade' }),
  phone: text('phone').notNull(),
  normalizedPhone: text('normalized_phone').notNull(),
  isPrimary: boolean('is_primary').notNull().default(false),
  isDoNotCall: boolean('is_do_not_call').notNull().default(false),
  isWrongNumber: boolean('is_wrong_number').notNull().default(false),
  channelConsentJson: jsonb('channel_consent_json').notNull().default({}),
  sourceType: text('source_type'),
  sourceReference: text('source_reference'),
  observedAt: timestamp('observed_at', { withTimezone: true }),
  effectiveAt: timestamp('effective_at', { withTimezone: true }),
  retiredAt: timestamp('retired_at', { withTimezone: true }),
  createdByUserId: uuid('created_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  contactPhoneIdx: uniqueIndex('contact_phone_numbers_contact_phone_idx').on(
    table.organizationId,
    table.contactId,
    table.normalizedPhone,
  ),
  contactPrimaryIdx: uniqueIndex('contact_phone_numbers_contact_primary_idx')
    .on(table.organizationId, table.contactId)
    .where(sql`${table.isPrimary} = true`),
  orgPhoneIdx: index('contact_phone_numbers_org_phone_idx').on(table.organizationId, table.normalizedPhone),
  businessUnitIdx: index('contact_phone_numbers_business_unit_idx').on(table.businessUnitId),
}));

export const contactChannelConsents = pgTable('contact_channel_consents', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  contactId: uuid('contact_id').notNull().references(() => contacts.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  scopeKey: text('scope_key').notNull().default('organization'),
  channel: text('channel').notNull(),
  consentStatus: text('consent_status').notNull().default('unknown'),
  optInSource: text('opt_in_source'),
  optInReference: text('opt_in_reference'),
  optInDisclosureText: text('opt_in_disclosure_text'),
  optInOccurredAt: timestamp('opt_in_occurred_at', { withTimezone: true }),
  optOutSource: text('opt_out_source'),
  optOutReference: text('opt_out_reference'),
  optOutReason: text('opt_out_reason'),
  optOutOccurredAt: timestamp('opt_out_occurred_at', { withTimezone: true }),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  contactChannelScopeIdx: uniqueIndex('contact_channel_consents_contact_channel_scope_idx').on(
    table.organizationId,
    table.contactId,
    table.channel,
    table.scopeKey,
  ),
  orgChannelStatusIdx: index('contact_channel_consents_org_channel_status_idx').on(
    table.organizationId,
    table.channel,
    table.consentStatus,
  ),
  businessUnitIdx: index('contact_channel_consents_business_unit_idx').on(table.businessUnitId),
}));

export const contactChannelConsentEvents = pgTable('contact_channel_consent_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  contactId: uuid('contact_id').notNull().references(() => contacts.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  scopeKey: text('scope_key').notNull().default('organization'),
  channel: text('channel').notNull(),
  eventType: text('event_type').notNull(),
  consentStatus: text('consent_status').notNull().default('unknown'),
  sourceType: text('source_type'),
  sourceReference: text('source_reference'),
  actorUserId: uuid('actor_user_id').references(() => users.id, { onDelete: 'set null' }),
  provider: text('provider'),
  providerEventId: text('provider_event_id'),
  idempotencyKey: text('idempotency_key'),
  disclosureText: text('disclosure_text'),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
  createdAt,
}, (table) => ({
  orgIdempotencyIdx: uniqueIndex('contact_channel_consent_events_org_idempotency_idx').on(
    table.organizationId,
    table.idempotencyKey,
  ),
  contactOccurredIdx: index('contact_channel_consent_events_contact_occurred_idx').on(
    table.contactId,
    table.occurredAt,
  ),
  orgChannelOccurredIdx: index('contact_channel_consent_events_org_channel_occurred_idx').on(
    table.organizationId,
    table.channel,
    table.occurredAt,
  ),
}));

export const contactPeople = pgTable('contact_people', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  contactId: uuid('contact_id').notNull().references(() => contacts.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  role: text('role'),
  phone: text('phone'),
  email: text('email'),
  notes: text('notes'),
  isPrimary: boolean('is_primary').notNull().default(false),
  sourceLabel: text('source_label'),
  sourceSheet: text('source_sheet'),
  sourceRow: integer('source_row'),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  contactIdx: index('contact_people_contact_idx').on(table.contactId),
  orgNameIdx: index('contact_people_org_name_idx').on(table.organizationId, table.name),
  sourceIdx: index('contact_people_source_idx').on(table.sourceSheet, table.sourceRow),
}));

export const leads = pgTable('leads', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'set null' }),
  sourceType: text('source_type').notNull(),
  sourceName: text('source_name'),
  status: text('status').notNull(),
  currentStage: text('current_stage'),
  assignedUserId: uuid('assigned_user_id').references(() => users.id, { onDelete: 'set null' }),
  originalNotes: text('original_notes'),
  programInterest: text('program_interest'),
  preferredDay: text('preferred_day'),
  preferredSchedule: text('preferred_schedule'),
  testInterest: text('test_interest'),
  educationLevel: text('education_level'),
  schoolName: text('school_name'),
  locationPreference: text('location_preference'),
  profileDetails: text('profile_details'),
  sourceDetail: text('source_detail'),
  currentCourse: text('current_course'),
  completedCourse: text('completed_course'),
  endedCourse: text('ended_course'),
  courseOutcome: text('course_outcome'),
  createdAt,
  updatedAt,
});

export const contactCourseRecords = pgTable('contact_course_records', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  contactId: uuid('contact_id').notNull().references(() => contacts.id, { onDelete: 'cascade' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  courseName: text('course_name').notNull(),
  courseLocation: text('course_location'),
  teacher: text('teacher'),
  status: text('status').notNull().default('active'),
  startDate: date('start_date'),
  endDate: date('end_date'),
  outcomeReason: text('outcome_reason'),
  notes: text('notes'),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  contactIdx: index('contact_course_records_contact_idx').on(table.organizationId, table.contactId),
  contactStatusIdx: index('contact_course_records_contact_status_idx').on(table.contactId, table.status),
  businessUnitStatusIdx: index('contact_course_records_business_unit_status_idx').on(table.businessUnitId, table.status),
  leadIdx: index('contact_course_records_lead_idx').on(table.leadId),
}));

export const leadStatusHistory = pgTable('lead_status_history', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'set null' }),
  leadId: uuid('lead_id').notNull().references(() => leads.id, { onDelete: 'cascade' }),
  fromStatus: text('from_status'),
  toStatus: text('to_status').notNull(),
  actorUserId: uuid('actor_user_id').references(() => users.id, { onDelete: 'set null' }),
  reason: text('reason'),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
  createdAt,
}, (table) => ({
  leadOccurredIdx: index('lead_status_history_lead_occurred_idx').on(table.leadId, table.occurredAt),
  orgOccurredIdx: index('lead_status_history_org_occurred_idx').on(table.organizationId, table.occurredAt),
  contactOccurredIdx: index('lead_status_history_contact_occurred_idx').on(table.contactId, table.occurredAt),
}));

export const notifications = pgTable('notifications', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }),
  type: text('type').notNull(),
  sourceType: text('source_type'),
  title: text('title').notNull(),
  body: text('body'),
  href: text('href'),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'set null' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  idempotencyKey: text('idempotency_key'),
  readAt: timestamp('read_at', { withTimezone: true }),
  createdAt,
  updatedAt,
}, (table) => ({
  orgReadCreatedIdx: index('notifications_org_read_created_idx').on(table.organizationId, table.readAt, table.createdAt),
  orgBusinessUnitCreatedIdx: index('notifications_org_business_unit_created_idx').on(table.organizationId, table.businessUnitId, table.createdAt),
  orgIdempotencyIdx: uniqueIndex('notifications_org_idempotency_idx').on(table.organizationId, table.idempotencyKey),
}));

export const estimates = pgTable('estimates', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'set null' }),
  estimateNumber: text('estimate_number'),
  status: text('status').notNull(),
  subtotal: numeric('subtotal', { precision: 12, scale: 2 }),
  tax: numeric('tax', { precision: 12, scale: 2 }),
  total: numeric('total', { precision: 12, scale: 2 }),
  advancePaid: numeric('advance_paid', { precision: 12, scale: 2 }),
  balanceDue: numeric('balance_due', { precision: 12, scale: 2 }),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  rejectedAt: timestamp('rejected_at', { withTimezone: true }),
  createdAt,
  updatedAt,
});

export const workOrders = pgTable('work_orders', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  estimateId: uuid('estimate_id').references(() => estimates.id, { onDelete: 'set null' }),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'set null' }),
  workOrderNumber: text('work_order_number'),
  title: text('title'),
  status: text('status').notNull(),
  priority: text('priority'),
  description: text('description'),
  estimatedCost: numeric('estimated_cost', { precision: 12, scale: 2 }),
  assignedUserId: uuid('assigned_user_id').references(() => users.id, { onDelete: 'set null' }),
  designerUserId: uuid('designer_user_id').references(() => users.id, { onDelete: 'set null' }),
  chiefUserId: uuid('chief_user_id').references(() => users.id, { onDelete: 'set null' }),
  deliveryDate: date('delivery_date'),
  createdAt,
  updatedAt,
});

export const financialDocuments = pgTable('financial_documents', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'set null' }),
  workOrderId: uuid('work_order_id').references(() => workOrders.id, { onDelete: 'set null' }),
  estimateId: uuid('estimate_id').references(() => estimates.id, { onDelete: 'set null' }),
  documentNumber: text('document_number'),
  documentType: text('document_type').notNull(),
  status: text('status').notNull().default('Draft'),
  subtotal: numeric('subtotal', { precision: 12, scale: 2 }),
  tax: numeric('tax', { precision: 12, scale: 2 }),
  total: numeric('total', { precision: 12, scale: 2 }),
  paidAmount: numeric('paid_amount', { precision: 12, scale: 2 }),
  balanceDue: numeric('balance_due', { precision: 12, scale: 2 }),
  issueDate: date('issue_date'),
  dueDate: date('due_date'),
  itemsJson: jsonb('items_json').notNull().default([]),
  notes: text('notes'),
  createdAt,
  updatedAt,
}, (table) => ({
  orgCreatedIdx: index('financial_documents_org_created_idx').on(table.organizationId, table.createdAt),
  contactIdx: index('financial_documents_contact_idx').on(table.contactId),
  workOrderIdx: index('financial_documents_work_order_idx').on(table.workOrderId),
  typeIdx: index('financial_documents_type_idx').on(table.documentType),
}));

export const paymentSnapshots = pgTable('payment_snapshots', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  estimateId: uuid('estimate_id').references(() => estimates.id, { onDelete: 'set null' }),
  workOrderId: uuid('work_order_id').references(() => workOrders.id, { onDelete: 'set null' }),
  paymentNumber: integer('payment_number'),
  paymentMethod: text('payment_method'),
  checkNumber: text('check_number'),
  amount: numeric('amount', { precision: 12, scale: 2 }),
  paidAt: date('paid_at'),
  balanceAfter: numeric('balance_after', { precision: 12, scale: 2 }),
  sourceSheet: text('source_sheet'),
  sourceRow: integer('source_row'),
  createdAt,
  updatedAt,
});

export const activityEvents = pgTable('activity_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'set null' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  estimateId: uuid('estimate_id').references(() => estimates.id, { onDelete: 'set null' }),
  workOrderId: uuid('work_order_id').references(() => workOrders.id, { onDelete: 'set null' }),
  eventType: text('event_type').notNull(),
  message: text('message'),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  actorUserId: uuid('actor_user_id').references(() => users.id, { onDelete: 'set null' }),
  sourceSheet: text('source_sheet'),
  sourceRow: integer('source_row'),
  occurredAt: timestamp('occurred_at', { withTimezone: true }),
  createdAt,
});

export const notes = pgTable('notes', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'set null' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  estimateId: uuid('estimate_id').references(() => estimates.id, { onDelete: 'set null' }),
  workOrderId: uuid('work_order_id').references(() => workOrders.id, { onDelete: 'set null' }),
  body: text('body').notNull(),
  authorUserId: uuid('author_user_id').references(() => users.id, { onDelete: 'set null' }),
  createdAt,
  updatedAt,
});

export const tasks = pgTable('tasks', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'set null' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  workOrderId: uuid('work_order_id').references(() => workOrders.id, { onDelete: 'set null' }),
  title: text('title').notNull(),
  description: text('description'),
  taskType: text('task_type').notNull(),
  status: text('status').notNull().default('open'),
  priority: text('priority').notNull().default('medium'),
  dueAt: timestamp('due_at', { withTimezone: true }),
  snoozedUntil: timestamp('snoozed_until', { withTimezone: true }),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  canceledAt: timestamp('canceled_at', { withTimezone: true }),
  ownerUserId: uuid('owner_user_id').references(() => users.id, { onDelete: 'set null' }),
  createdByUserId: uuid('created_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  sourceType: text('source_type'),
  sourceId: text('source_id'),
  sourceLabel: text('source_label'),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  orgStatusDueIdx: index('tasks_org_status_due_idx').on(table.organizationId, table.status, table.dueAt),
  businessUnitStatusDueIdx: index('tasks_business_unit_status_due_idx').on(table.businessUnitId, table.status, table.dueAt),
  ownerStatusDueIdx: index('tasks_owner_status_due_idx').on(table.ownerUserId, table.status, table.dueAt),
  contactIdx: index('tasks_contact_idx').on(table.contactId),
  leadIdx: index('tasks_lead_idx').on(table.leadId),
  workOrderIdx: index('tasks_work_order_idx').on(table.workOrderId),
}));

export const taskEvents = pgTable('task_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  taskId: uuid('task_id').notNull().references(() => tasks.id, { onDelete: 'cascade' }),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  eventType: text('event_type').notNull(),
  fromStatus: text('from_status'),
  toStatus: text('to_status'),
  fromOwnerUserId: uuid('from_owner_user_id').references(() => users.id, { onDelete: 'set null' }),
  toOwnerUserId: uuid('to_owner_user_id').references(() => users.id, { onDelete: 'set null' }),
  fromDueAt: timestamp('from_due_at', { withTimezone: true }),
  toDueAt: timestamp('to_due_at', { withTimezone: true }),
  actorUserId: uuid('actor_user_id').references(() => users.id, { onDelete: 'set null' }),
  message: text('message'),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
  createdAt,
}, (table) => ({
  taskOccurredIdx: index('task_events_task_occurred_idx').on(table.taskId, table.occurredAt),
  orgOccurredIdx: index('task_events_org_occurred_idx').on(table.organizationId, table.occurredAt),
}));

export const conversationChannels = pgTable('conversation_channels', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  channel: text('channel').notNull(),
  provider: text('provider').notNull(),
  providerAccountId: text('provider_account_id').notNull(),
  label: text('label'),
  isActive: boolean('is_active').notNull().default(true),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  orgProviderAccountIdx: uniqueIndex('conversation_channels_org_provider_account_idx').on(
    table.organizationId,
    table.provider,
    table.channel,
    table.providerAccountId,
  ),
  businessUnitIdx: index('conversation_channels_business_unit_idx').on(table.businessUnitId),
}));

export const conversations = pgTable('conversations', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'set null' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  channelId: uuid('channel_id').references(() => conversationChannels.id, { onDelete: 'set null' }),
  channel: text('channel').notNull(),
  provider: text('provider').notNull(),
  providerAccountId: text('provider_account_id').notNull(),
  providerThreadId: text('provider_thread_id').notNull(),
  externalParticipantId: text('external_participant_id').notNull(),
  status: text('status').notNull().default('open'),
  lastMessageAt: timestamp('last_message_at', { withTimezone: true }),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  providerConversationIdx: uniqueIndex('conversations_provider_conversation_idx').on(
    table.organizationId,
    table.provider,
    table.channel,
    table.providerAccountId,
    table.providerThreadId,
    table.externalParticipantId,
  ),
  contactLastMessageIdx: index('conversations_contact_last_message_idx').on(table.contactId, table.lastMessageAt),
  leadLastMessageIdx: index('conversations_lead_last_message_idx').on(table.leadId, table.lastMessageAt),
  businessUnitStatusIdx: index('conversations_business_unit_status_idx').on(table.businessUnitId, table.status),
}));

export const conversationMessages = pgTable('conversation_messages', {
  id: uuid('id').primaryKey().defaultRandom(),
  conversationId: uuid('conversation_id').notNull().references(() => conversations.id, { onDelete: 'cascade' }),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'set null' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  channel: text('channel').notNull(),
  provider: text('provider').notNull(),
  direction: text('direction').notNull(),
  deliveryStatus: text('delivery_status').notNull(),
  providerAccountId: text('provider_account_id').notNull(),
  providerThreadId: text('provider_thread_id').notNull(),
  externalMessageId: text('external_message_id'),
  idempotencyKey: text('idempotency_key').notNull(),
  senderIdentity: text('sender_identity'),
  recipientIdentity: text('recipient_identity'),
  textBody: text('text_body'),
  rawPayloadJson: jsonb('raw_payload_json').notNull().default({}),
  errorCode: text('error_code'),
  errorMessage: text('error_message'),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
  createdAt,
  updatedAt,
}, (table) => ({
  providerMessageIdx: uniqueIndex('conversation_messages_provider_message_idx').on(
    table.organizationId,
    table.provider,
    table.channel,
    table.idempotencyKey,
  ),
  conversationOccurredIdx: index('conversation_messages_conversation_occurred_idx').on(table.conversationId, table.occurredAt),
  contactOccurredIdx: index('conversation_messages_contact_occurred_idx').on(table.contactId, table.occurredAt),
  leadOccurredIdx: index('conversation_messages_lead_occurred_idx').on(table.leadId, table.occurredAt),
  businessUnitStatusIdx: index('conversation_messages_business_unit_status_idx').on(table.businessUnitId, table.deliveryStatus),
}));

export const messageTemplates = pgTable('message_templates', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'cascade' }),
  channel: text('channel').notNull().default('all'),
  purpose: text('purpose').notNull(),
  displayName: text('display_name').notNull(),
  bodyText: text('body_text').notNull(),
  status: text('status').notNull().default('draft'),
  providerStatus: text('provider_status').notNull().default('not_required'),
  isEnabled: boolean('is_enabled').notNull().default(false),
  createdByUserId: uuid('created_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  updatedByUserId: uuid('updated_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  orgChannelPurposeIdx: index('message_templates_org_channel_purpose_idx').on(
    table.organizationId,
    table.channel,
    table.purpose,
    table.status,
  ),
  businessUnitIdx: index('message_templates_business_unit_idx').on(table.businessUnitId),
}));

export const messageChannelSettings = pgTable('message_channel_settings', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'cascade' }),
  scopeKey: text('scope_key').notNull(),
  intakeRouteKey: text('intake_route_key').notNull().default('default'),
  channel: text('channel').notNull(),
  isEnabled: boolean('is_enabled').notNull().default(false),
  createdByUserId: uuid('created_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  updatedByUserId: uuid('updated_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  settingsJson: jsonb('settings_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  orgScopeChannelIdx: uniqueIndex('message_channel_settings_org_scope_channel_idx').on(
    table.organizationId,
    table.scopeKey,
    table.channel,
  ),
  businessUnitIdx: index('message_channel_settings_business_unit_idx').on(table.businessUnitId),
}));

export const followUpSequences = pgTable('follow_up_sequences', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'cascade' }),
  key: text('key').notNull(),
  name: text('name').notNull(),
  description: text('description'),
  status: text('status').notNull().default('draft'),
  defaultChannel: text('default_channel').notNull().default('messenger'),
  isEnabled: boolean('is_enabled').notNull().default(false),
  maxTouches: integer('max_touches').notNull().default(3),
  settingsJson: jsonb('settings_json').notNull().default({}),
  createdByUserId: uuid('created_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  updatedByUserId: uuid('updated_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  createdAt,
  updatedAt,
}, (table) => ({
  orgKeyIdx: uniqueIndex('follow_up_sequences_org_key_idx').on(table.organizationId, table.key),
  businessUnitIdx: index('follow_up_sequences_business_unit_idx').on(table.businessUnitId),
}));

export const followUpSequenceSteps = pgTable('follow_up_sequence_steps', {
  id: uuid('id').primaryKey().defaultRandom(),
  sequenceId: uuid('sequence_id').notNull().references(() => followUpSequences.id, { onDelete: 'cascade' }),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  stepKey: text('step_key').notNull(),
  position: integer('position').notNull(),
  delayMinutes: integer('delay_minutes').notNull().default(1440),
  channel: text('channel').notNull().default('messenger'),
  templateId: uuid('template_id').references(() => messageTemplates.id, { onDelete: 'set null' }),
  actionType: text('action_type').notNull().default('task_and_draft'),
  taskTitle: text('task_title').notNull(),
  taskDescription: text('task_description'),
  isActive: boolean('is_active').notNull().default(true),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  sequencePositionIdx: uniqueIndex('follow_up_sequence_steps_sequence_position_idx').on(table.sequenceId, table.position),
  sequenceStepKeyIdx: uniqueIndex('follow_up_sequence_steps_sequence_key_idx').on(table.sequenceId, table.stepKey),
}));

export const followUpSequenceEnrollments = pgTable('follow_up_sequence_enrollments', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  sequenceId: uuid('sequence_id').notNull().references(() => followUpSequences.id, { onDelete: 'cascade' }),
  contactId: uuid('contact_id').notNull().references(() => contacts.id, { onDelete: 'cascade' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  status: text('status').notNull().default('active'),
  channel: text('channel').notNull(),
  ownerUserId: uuid('owner_user_id').references(() => users.id, { onDelete: 'set null' }),
  enrolledByUserId: uuid('enrolled_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  triggerType: text('trigger_type').notNull().default('manual'),
  nextStepPosition: integer('next_step_position').notNull().default(1),
  nextStepDueAt: timestamp('next_step_due_at', { withTimezone: true }).notNull(),
  touchCount: integer('touch_count').notNull().default(0),
  maxTouches: integer('max_touches').notNull().default(3),
  pausedUntil: timestamp('paused_until', { withTimezone: true }),
  stoppedAt: timestamp('stopped_at', { withTimezone: true }),
  stopReason: text('stop_reason'),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  enrolledAt: timestamp('enrolled_at', { withTimezone: true }).notNull().defaultNow(),
  createdAt,
  updatedAt,
}, (table) => ({
  orgStatusDueIdx: index('follow_up_sequence_enrollments_org_status_due_idx').on(
    table.organizationId,
    table.status,
    table.nextStepDueAt,
  ),
  contactStatusIdx: index('follow_up_sequence_enrollments_contact_status_idx').on(table.contactId, table.status),
  businessUnitStatusIdx: index('follow_up_sequence_enrollments_business_unit_status_idx').on(table.businessUnitId, table.status),
  activeContactSequenceIdx: uniqueIndex('follow_up_sequence_enrollments_active_contact_sequence_idx')
    .on(table.organizationId, table.sequenceId, table.contactId)
    .where(sql`${table.status} = 'active'`),
}));

export const followUpSequenceStepRuns = pgTable('follow_up_sequence_step_runs', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  sequenceId: uuid('sequence_id').notNull().references(() => followUpSequences.id, { onDelete: 'cascade' }),
  enrollmentId: uuid('enrollment_id').notNull().references(() => followUpSequenceEnrollments.id, { onDelete: 'cascade' }),
  stepId: uuid('step_id').notNull().references(() => followUpSequenceSteps.id, { onDelete: 'cascade' }),
  contactId: uuid('contact_id').notNull().references(() => contacts.id, { onDelete: 'cascade' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  taskId: uuid('task_id').references(() => tasks.id, { onDelete: 'set null' }),
  status: text('status').notNull(),
  dueAt: timestamp('due_at', { withTimezone: true }).notNull(),
  executedAt: timestamp('executed_at', { withTimezone: true }),
  idempotencyKey: text('idempotency_key').notNull(),
  draftMessageJson: jsonb('draft_message_json').notNull().default({}),
  blockedReason: text('blocked_reason'),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  idempotencyIdx: uniqueIndex('follow_up_sequence_step_runs_idempotency_idx').on(table.organizationId, table.idempotencyKey),
  enrollmentStepIdx: index('follow_up_sequence_step_runs_enrollment_step_idx').on(table.enrollmentId, table.stepId),
  orgStatusIdx: index('follow_up_sequence_step_runs_org_status_idx').on(table.organizationId, table.status),
}));

export const smsCampaigns = pgTable('sms_campaigns', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  status: text('status').notNull().default('draft'),
  audienceFilterJson: jsonb('audience_filter_json').notNull().default({}),
  messageBody: text('message_body').notNull(),
  senderProvider: text('sender_provider').notNull().default('telnyx'),
  senderAccountId: text('sender_account_id'),
  sendWindowJson: jsonb('send_window_json').notNull().default({}),
  throttlePerHour: integer('throttle_per_hour').notNull().default(120),
  providerReadinessJson: jsonb('provider_readiness_json').notNull().default({}),
  complianceReadinessJson: jsonb('compliance_readiness_json').notNull().default({}),
  approvedByUserId: uuid('approved_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  approvedAt: timestamp('approved_at', { withTimezone: true }),
  scheduledAt: timestamp('scheduled_at', { withTimezone: true }),
  launchedAt: timestamp('launched_at', { withTimezone: true }),
  pausedAt: timestamp('paused_at', { withTimezone: true }),
  cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  createdByUserId: uuid('created_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  updatedByUserId: uuid('updated_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  orgStatusIdx: index('sms_campaigns_org_status_idx').on(table.organizationId, table.status),
  businessUnitStatusIdx: index('sms_campaigns_business_unit_status_idx').on(table.businessUnitId, table.status),
  scheduledIdx: index('sms_campaigns_scheduled_idx').on(table.organizationId, table.scheduledAt),
}));

export const smsCampaignRecipients = pgTable('sms_campaign_recipients', {
  id: uuid('id').primaryKey().defaultRandom(),
  campaignId: uuid('campaign_id').notNull().references(() => smsCampaigns.id, { onDelete: 'cascade' }),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').notNull().references(() => businessUnits.id, { onDelete: 'cascade' }),
  contactId: uuid('contact_id').references(() => contacts.id, { onDelete: 'set null' }),
  leadId: uuid('lead_id').references(() => leads.id, { onDelete: 'set null' }),
  phone: text('phone').notNull(),
  normalizedPhone: text('normalized_phone').notNull(),
  eligibilityStatus: text('eligibility_status').notNull(),
  blockedReasonsJson: jsonb('blocked_reasons_json').notNull().default([]),
  messagePreview: text('message_preview'),
  deliveryStatus: text('delivery_status').notNull().default('not_queued'),
  provider: text('provider'),
  providerAccountId: text('provider_account_id'),
  providerMessageId: text('provider_message_id'),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
  updatedAt,
}, (table) => ({
  campaignContactIdx: uniqueIndex('sms_campaign_recipients_campaign_contact_idx').on(table.campaignId, table.contactId),
  campaignPhoneIdx: index('sms_campaign_recipients_campaign_phone_idx').on(table.campaignId, table.normalizedPhone),
  campaignStatusIdx: index('sms_campaign_recipients_campaign_status_idx').on(table.campaignId, table.eligibilityStatus),
}));

export const smsCampaignEvents = pgTable('sms_campaign_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  campaignId: uuid('campaign_id').notNull().references(() => smsCampaigns.id, { onDelete: 'cascade' }),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  eventType: text('event_type').notNull(),
  fromStatus: text('from_status'),
  toStatus: text('to_status'),
  actorUserId: uuid('actor_user_id').references(() => users.id, { onDelete: 'set null' }),
  message: text('message'),
  metadataJson: jsonb('metadata_json').notNull().default({}),
  createdAt,
}, (table) => ({
  campaignCreatedIdx: index('sms_campaign_events_campaign_created_idx').on(table.campaignId, table.createdAt),
  orgEventIdx: index('sms_campaign_events_org_event_idx').on(table.organizationId, table.eventType),
}));

export const files = pgTable('files', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  recordType: text('record_type').notNull(),
  recordId: uuid('record_id').notNull(),
  storageKey: text('storage_key').notNull(),
  filename: text('filename').notNull(),
  mimeType: text('mime_type'),
  sizeBytes: bigint('size_bytes', { mode: 'number' }),
  createdAt,
});

export const importBatches = pgTable('import_batches', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id, { onDelete: 'cascade' }),
  businessUnitId: uuid('business_unit_id').references(() => businessUnits.id, { onDelete: 'set null' }),
  sourceName: text('source_name').notNull(),
  sourceType: text('source_type').notNull(),
  fileName: text('file_name').notNull(),
  fileHash: text('file_hash'),
  sheetName: text('sheet_name'),
  status: text('status').notNull(),
  createdByUserId: uuid('created_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  createdAt,
}, (table) => ({
  businessUnitIdx: index('import_batches_business_unit_idx').on(table.businessUnitId),
}));

export const importSourceRows = pgTable('import_source_rows', {
  id: uuid('id').primaryKey().defaultRandom(),
  importBatchId: uuid('import_batch_id').notNull().references(() => importBatches.id, { onDelete: 'cascade' }),
  sourceSheet: text('source_sheet').notNull(),
  sourceRowNumber: integer('source_row_number').notNull(),
  rawValuesJson: jsonb('raw_values_json').notNull(),
  rawText: text('raw_text'),
  parseStatus: text('parse_status').notNull().default('pending'),
  createdAt,
});

export const importNormalizedRecords = pgTable('import_normalized_records', {
  id: uuid('id').primaryKey().defaultRandom(),
  importBatchId: uuid('import_batch_id').notNull().references(() => importBatches.id, { onDelete: 'cascade' }),
  sourceRowId: uuid('source_row_id').notNull().references(() => importSourceRows.id, { onDelete: 'cascade' }),
  recordType: text('record_type').notNull(),
  proposedContactJson: jsonb('proposed_contact_json'),
  proposedLeadJson: jsonb('proposed_lead_json'),
  proposedEstimateJson: jsonb('proposed_estimate_json'),
  proposedWorkOrderJson: jsonb('proposed_work_order_json'),
  proposedPaymentJson: jsonb('proposed_payment_json'),
  proposedNoteJson: jsonb('proposed_note_json'),
  confidenceScore: numeric('confidence_score', { precision: 5, scale: 2 }),
  status: text('status').notNull().default('pending'),
  createdAt,
});

export const importReviewItems = pgTable('import_review_items', {
  id: uuid('id').primaryKey().defaultRandom(),
  importBatchId: uuid('import_batch_id').notNull().references(() => importBatches.id, { onDelete: 'cascade' }),
  sourceRowId: uuid('source_row_id').references(() => importSourceRows.id, { onDelete: 'cascade' }),
  reviewType: text('review_type').notNull(),
  reason: text('reason').notNull(),
  proposedResolutionJson: jsonb('proposed_resolution_json'),
  reviewStatus: text('review_status').notNull().default('pending'),
  reviewedByUserId: uuid('reviewed_by_user_id').references(() => users.id, { onDelete: 'set null' }),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  createdAt,
  updatedAt,
});

export const allTables = {
  organizations,
  businessUnits,
  users,
  userPasswordCredentials,
  userSessions,
  roles,
  permissions,
  rolePermissions,
  userRoles,
  businessUnitMemberships,
  contacts,
  contactPhoneNumbers,
  contactChannelConsents,
  contactChannelConsentEvents,
  contactPeople,
  leads,
  contactCourseRecords,
  leadStatusHistory,
  notifications,
  estimates,
  workOrders,
  paymentSnapshots,
  activityEvents,
  notes,
  tasks,
  taskEvents,
  conversationChannels,
  conversations,
  conversationMessages,
  messageTemplates,
  messageChannelSettings,
  followUpSequences,
  followUpSequenceSteps,
  followUpSequenceEnrollments,
  followUpSequenceStepRuns,
  smsCampaigns,
  smsCampaignRecipients,
  smsCampaignEvents,
  files,
  importBatches,
  importSourceRows,
  importNormalizedRecords,
  importReviewItems,
};
